source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/laichunhui/SYSpecs.git' #私有仓库

use_frameworks!

target 'YourFilm_Example' do

    # 私有库
    pod 'SYKit', :git => 'https://gitee.com/laichunhui/SYKit.git'
    pod 'SnapKit'

  target 'YourFilm_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
